import Image from "next/image";
import Head from 'next/head'
import { gql } from "@apollo/client";
import client from "../apollo-client";
import Link from "next/link";
import { useState, useEffect } from "react";
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css'
import classes from '../styles/form.module.css'
import useForm from "../utility/useForm";
export default function Home({users}) {
  const [isRefreshing, setIsRefreshing] = useState(false);
  const router = useRouter();
 /* const refreshData = () => {
    router.replace(router.asPath);
  }*/
  const refreshData = () => {
    router.replace(router.asPath);
    setIsRefreshing(true);
  };
  useEffect(() => {
    setIsRefreshing(false);
  }, [users]);

  const { inputs, handleChange, clearForm } = useForm({
    LOGIN: "",
    AVATAR_URL: "",
  })
  async function sendData(event) {
    event.preventDefault();
    try {
      const result = await client.mutate({
        mutation: gql`
        mutation CreateUser {
          createUser(LOGIN: "${inputs.LOGIN}", AVATAR_URL: "${inputs.AVATAR_URL}") {
              ID
              LOGIN
              AVATAR_URL
            }
          }
        `,
      });
      console.log(result);
    
      refreshData();  
      clearForm()
    } catch (error) {
      console.log(error.message);
    }
  }
  async function deleteUser(id) {
    try {
      const result = await client.mutate({
        mutation: gql`
        mutation DeleteUser {
          deleteUser(ID: "${id}") 
          }
        `,
      });
      console.log(result);
      refreshData()
    } catch (error) {
      console.log(error.message);
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <h1 className={styles.title}>  Next.js example with graphql and firebird</h1>
        <p className={styles.description}>
                 <strong>Using Apollo Client for server side rendered page data</strong>
                 <br></br><br></br>
                 Fetching data for server-side generated pages is done using the getServerSideProps method provided by Next.js. This function will be used during each page request to get any data passed into the page component as props.
        </p>
   
       

      <form onSubmit={sendData} className={classes.form}>
      <div className={classes.title}>New user</div>
        <div className={`${classes.input_container} ${classes.ic1}`}>
          
          <input
          className={classes.input}
          placeholder="Name"
            type={"text"}
            name="LOGIN"
            value={inputs.LOGIN}
            onChange={handleChange}
          ></input>
        </div>

        <div className={`${classes.input_container} ${classes.ic2}`}>
        
          <input
            className={classes.input}
            placeholder="Avatar"
            type={"text"}
            name="AVATAR_URL"
            value={inputs.AVATAR_URL}
            onChange={handleChange}
          ></input>
        </div>
        <br></br>
        <button className={classes.submit} type="submit">create user</button>
      </form>
      <h2>Users</h2>
      <div className={styles.grid}>
        {users.map((el) => {
          return (
            <div key={el.ID}  className={styles.card}>
              <h3><Link href={`/user/${el.ID}`}>
                <a>{el.LOGIN}</a>
              </Link></h3>
              <Image
                width={50}
                height={50}
                src={el.AVATAR_URL}
                alt={el.LOGIN}
              />
              <br></br><br></br>
              <button onClick={() => deleteUser(el.ID)}>Delete</button>
            </div>
          );
        })}
      </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
      query GetUsers {
        getUsers {
          ID
          LOGIN
          AVATAR_URL
        }
      }
    `,
  });

  return {
    props: {
      users: data.getUsers,
    },
  };
}
